column_names:
- author
- is_submission
- is_submitter
- num_comments
- over_18
- tag
- text
- time_created
- score
- subreddit
min_length: 2000
paths:
  save_preprocessed_data: ./data/preprocessed_reddit_submissions.csv
  save_raw_data: ./data/raw_reddit_submissions.csv
reddit:
  client_id: YOUR_CLIENT_IR
  client_secret: YOUR_CLIENT_SECTER
  user_agent: YOUR_USER_AGENT
subreddit_names:
- psychotherapy
- 90s
- ABoringDystopia
- AcademicPsychology
- Acadiana
- AdviceAnimals
- AfterTheLoop
- AirForce
- AmITheDevil
- AmItheAsshole
- Amsterdam
- AnalogCommunity
- Anarchism
- AppleMusic
- ArtefactPorn
- AskARussian
- AskAnAmerican
- AskDocs
- AskEconomics
- AskEngineers
- AskFoodHistorians
- AskHistorians
- AskHistory
- AskMen
- AskOldPeople
- AskPhysics
- AskReddit
- AskScienceDiscussion
- AskSocialScience
- AskWomenOver30
- Ask_Politics
- Austin
- BDSMAdvice
- Baking
- BestofRedditorUpdates
- BlackPeopleTwitter
- BreakUps
- Buttcoin
- COVID19positive
- CPTSD
- Calgary
- CampingandHiking
- CasualConversation
- CasualUK
- CatastrophicFailure
- China
- ChronicIllness
- Coffee
- Columbus
- CombatFootage
- Conservative
- Cooking
- Coronavirus
- CoronavirusMa
- CredibleDefense
- CryptoCurrency
- CuratedTumblr
- Cyberpunk
- Damnthatsinteresting
- Denver
- Documentaries
- DoesAnybodyElse
- EconomicHistory
- Economics
- Fantasy
- Firearms
- Fishing
- FundieSnarkUncensored
- Futurology
- Games
- Gold
- GreenAndPleasant
- Gymnastics
- HermanCainAward
- HistoryMemes
- HistoryPorn
- HobbyDrama
- IDontWorkHereLady
- IWantToLearn
- IndianCountry
- Jeopardy
- JusticeServed
- Justrolledintotheshop
- LabourUK
- LateStageCapitalism
- Lawyertalk
- LeopardsAteMyFace
- LineageOS
- LosAngeles
- MadeMeCry
- MadeMeSmile
- Mafia
- MapPorn
- Marriage
- MensLib
- Military
- MilitaryStories
- MorbidHistory
- Music
- MuslimMarriage
- NarcoFootage
- NatureIsFuckingLit
- NoStupidQuestions
- NonBinary
- NonCredibleDefense
- Nordichistorymemes
- Norse
- NotHowGirlsWork
- OldSchoolCool
- OntarioCanada
- OrganicChemistry
- OutOfTheLoop
- ParlerWatch
- Portland
- Professors
- ProgrammerHumor
- PublicFreakout
- QAnonCasualties
- QuantumPhysics
- Qult_Headquarters
- RedditForGrownups
- Residency
- RomanceBooks
- SWORDS
- Scotland
- Screenwriting
- Seattle
- ShitLiberalsSay
- Showerthoughts
- Socialism_101
- SubredditDrama
- SweatyPalms
- Teachers
- ThatsInsane
- TheGirlSurvivalGuide
- TheLastKingdom
- TikTokCringe
- TooAfraidToAsk
- ToolBand
- Transmedical
- TrollXChromosomes
- TrueCrime
- TrueFilm
- TrueOffMyChest
- TwoBestFriendsPlay
- USMC
- UkraineWarVideoReport
- UpliftingNews
- WTF
- WarCollege
- WarshipPorn
- Warthunder
- WatchPeopleDieInside
- Watches
- Whatcouldgowrong
- WhatsWrongWithYourDog
- WhitePeopleTwitter
- Windows10
- YouShouldKnow
- anime_titties
- antiwork
- apple
- army
- askTO
- askdrugs
- askgaybros
- askphilosophy
- askscience
- asktransgender
- assassinscreed
- australia
- aviation
- aww
- axolotls
- badwomensanatomy
- bengals
- bestof
- bestoflegaladvice
- britishproblems
- canadahousing
- cancer
- chemistry
- chess
- cincinnati
- cna
- collapse
- coloradohikers
- confidentlyincorrect
- coolguides
- craftsnark
- creepy
- creepyencounters
- diabetes_t1
- duolingo
- ems
- environment
- espresso
- europe
- exchristian
- exvegans
- facepalm
- farming
- feemagers
- femalefashionadvice
- fountainpens
- fragrance
- funny
- gadgets
- gamedev
- gay_irl
- gifs
- goldenretrievers
- greentext
- harrypotter
- help
- history
- humansarespaceorcs
- insanepeoplefacebook
- interestingasfuck
- investing
- ireland
- justneckbeardthings
- languagelearning
- learnprogramming
- lexington
- linguistics
- medicalschool
- medicine
- medizzy
- meirl
- morbidquestions
- movies
- musicals
- musictheory
- mycology
- navy
- nba
- neoliberal
- newborns
- news
- nextfuckinglevel
- nocontextpics
- nottheonion
- nursing
- nutrition
- nyc
- olympics
- ontario
- opiates
- osr
- ottawa
- peopleofwalmart
- personalfinance
- photography
- physicsmemes
- pics
- polls
- popheads
- povertyfinance
- pregnant
- preppers
- programming
- relationship_advice
- science
- secularbuddhism
- self
- service_dogs
- singapore
- skeptic
- slowcooking
- socialism
- spacex
- specializedtools
- spiderbro
- talesfromtechsupport
- tasmania
- tech
- technology
- television
- thanksimcured
- therapists
- tifu
- todayilearned
- toddlers
- tooktoomuch
- traaaaaaannnnnnnnnns
- travel
- tumblr
- vexillology
- videos
- vultureculture
- weightlifting
- whatisthisthing
- worldnews
- wowthissubexists
- writing
- ww2
- yesyesyesno
- youtubehaiku
- 3Dprinting
- 80sdesign
- AccidentalWesAnderson
- AdorableArt
- Art
- ArtistLounge
- Blacksmith
- Bonsai
- DIY
- Design
- DiWHY
- DigitalPainting
- EarthPorn
- Embroidery
- Heavymind
- HelpMeFind
- HomeImprovement
- ICanDrawThat
- IDAP
- InteriorDesign
- InternetIsBeautiful
- MechanicAdvice
- OldSchoolCool
- PenmanshipPorn
- Plumbing
- RoomPorn
- SonyAlpha
- SpecArt
- Tools
- VaporwaveAesthetics
- blender
- conceptart
- coolguides
- graphic_design
- houseplants
- itookapicture
- learnart
- logodesign
- painting
- photomarket
- photoshop
- proplifting
- raining
- sewing
- tattoos
- typography
- vexillology
- videography
- web_design
- wyzecamATBGE
- AbandonedPorn
- AmateurRoomPorn
- ArchitecturePorn
- ArtCrit
- ArtFundamentals
- CozyPlaces
- CrappyDesign
- CrossStitch
- DesignPorn
- HomeKit
- MostBeautiful
- Pareidolia
- PhotoshopRequest
- PixelArt
- PlantedTank
- Sculpture
- Skookum
- Welding
- analog
- animation
- architecture
- assholedesign
- cactus
- chat
- cinematography
- comics
- computergraphics
- dontdeadopeninside
- doodles
- electronics
- ender3
- fixit
- functionalprint
- homestead
- howto
- lawncare
- minimalism
- minipainting
- modelmakers
- orchids
- photocritique
- photoshopbattles
- plantclinic
- postprocessing
- quilting
- visualization
- whatsthisplant
- ''
- 1200isplenty
- 2007scape
- 49ers
- 90DayFiance
- ACMilan
- Adelaide
- Amd
- Android
- Animesuggest
- AnthemTheGame
- AskCulinary
- AskNYC
- AskWomen
- Astros
- Atlanta
- AtlantaUnited
- Austria
- Barca
- BattlefieldV
- BeautyBoxes
- BeautyGuruChatter
- Berserk
- BigBrother
- BlackClover
- Blackops4
- BoJackHorseman
- BokuNoHeroAcademia
- Boruto
- BostonBruins
- Boxing
- Braves
- BravoRealHousewives
- Brawlstars
- Breath_of_the_Wild
- Brogress
- Browns
- C25K
- CFB
- CHIBears
- CHICubs
- CampingGear
- Cardinals
- Charlotte
- ClashOfClans
- ClashRoyale
- CoDCompetitive
- CollegeBasketball
- Competitiveoverwatch
- Cricket
- CrohnsDisease
- CrusaderKings
- DBZDokkanBattle
- DMAcademy
- Dallas
- DanLeBatardShow
- DaysGone
- Denmark
- Destiny
- DestinyTheGame
- Detroit
- Disneyland
- DnD
- Dodgers
- DotA2
- DuelLinks
- DunderMifflin
- DynastyFF
- EDH
- EDanonymemes
- EOOD
- EatCheapAndHealthy
- Edmonton
- EliteDangerous
- EscapefromTarkov
- Eve
- FFBraveExvius
- FIFA
- FORTnITE
- FUTMobile
- Fallout
- FantasyPL
- FireEmblemHeroes
- Fitness
- FixedGearBicycle
- FlashTV
- FortNiteBR
- FortniteCompetitive
- Frugal
- GameOfThronesMemes
- Gamingcirclejerk
- GetMotivated
- Glitch_in_the_Matrix
- GlobalOffensive
- GlobalOffensiveTrade
- GooglePixel
- GreenBayPackers
- Grimdank
- Guildwars2
- Gundam
- HBOGameofThrones
- Hair
- HealthyFood
- HomeImprovement
- IASIP
- IAmA
- IWantOut
- ImaginaryWesteros
- Indiemakeupandmore
- Instagram
- Israel
- JapanTravel
- Konosuba
- LearnJapanese
- LegendsOfTomorrow
- Less
- LifeProTips
- LigaMX
- LiverpoolFC
- LivestreamFail
- LosAngelesRams
- LushCosmetics
- MCFC
- MLBTheShow
- MLS
- MMA
- MTB
- MUAontheCheap
- MagicArena
- Makeup
- MakeupAddiction
- MakingaMurderer
- Market76
- MarvelStrikeForce
- Mavericks
- Minecraft
- Minneapolis
- MkeBucks
- ModernMagic
- MonsterHunterWorld
- Mordhau
- MortalKombat
- MtvChallenge
- NBA2k
- NBASpurs
- NFA
- NHLHUT
- NYKnicks
- NYYankees
- Naruto
- Nationals
- Nerf
- NetflixBestOf
- NewOrleans
- NewSkaters
- NewYorkMets
- NintendoSwitch
- NoMansSkyTheGame
- OnePiece
- Overwatch
- PS4
- PSVR
- PUBATTLEGROUNDS
- PUBGMobile
- Paladins
- PanPorn
- PandR
- Patriots
- Persona5
- Philippines
- Planetside
- Polska
- Quebec
- RWBY
- Rainbow6
- RedDeadOnline
- RedditLaqueristas
- RepLadiesBST
- Repsneakers
- RimWorld
- RocketLeague
- RocketLeagueExchange
- Romania
- Rowing
- SFGiants
- SWGalaxyOfHeroes
- Sacramento
- SaltLakeCity
- SanJoseSharks
- SarahSnark
- Seaofthieves
- SequelMemes
- ShingekiNoKyojin
- Shoestring
- Smite
- Sneakers
- Spiderman
- SpoiledDragRace
- SquaredCircle
- StLouis
- StarVStheForcesofEvil
- StarWarsBattlefront
- StardewValley
- Steam
- Stellaris
- StrangerThings
- Stronglifts5x5
- Suomi
- Supplements
- TeenMomOGandTeenMom2
- Terraria
- TheAmazingRace
- TheBlackList
- TheDickShow
- TheHandmaidsTale
- TheLastAirbender
- TheSimpsons
- Tinder
- Torontobluejays
- Turkey
- TurkeyJerky
- Twitch
- VictoriaBC
- WWE
- WWEGames
- WaltDisneyWorld
- Warframe
- Warhammer40k
- Watchexchange
- Wellington
- Wetshaving
- Winnipeg
- WorldOfWarships
- WorldofTanks
- Youniqueamua
- aSongOfMemesAndRage
- acne
- adventuretime
- airsoft
- amateur_boxing
- anime
- anime_irl
- argentina
- arrow
- asoiaf
- awardtravel
- backpacking
- balisong
- barstoolsports
- baseball
- batman
- battlestations
- bayarea
- beards
- beauty
- berkeley
- bicycling
- bikecommuting
- bikewrench
- bjj
- blackmirror
- bleach
- boardgames
- bodybuilding
- bodyweightfitness
- books
- boostedboards
- bostonceltics
- brasil
- brasilivre
- breakingbad
- brisbane
- brooklynninenine
- buildapc
- camping
- canada
- canucks
- cars
- chelseafc
- chile
- cirkeltrek
- classicwow
- climbing
- community
- confession
- cordcutters
- cowboys
- coys
- criterion
- croatia
- crossfit
- cscareerquestions
- curlyhair
- cycling
- danganronpa
- dauntless
- dbz
- de
- deadbydaylight
- denvernuggets
- destiny2
- detroitlions
- diabetes
- discgolf
- discordapp
- disney
- dndmemes
- dndnext
- doctorwho
- dubai
- eagles
- ehlersdanlos
- elderscrollsonline
- eu4
- explainlikeimfive
- fairytail
- fantasybaseball
- fantasyfootball
- fasting
- femalehairadvice
- ffxiv
- findfashion
- fireemblem
- fivenightsatfreddys
- flexibility
- flightsim
- flyfishing
- fo76
- footballmanagergames
- forhonor
- formula1
- france
- freefolk
- frugalmalefashion
- futurama
- future_fight
- gainit
- gameofthrones
- germany
- girlsfrontline
- golf
- goodyearwelt
- grandorder
- greece
- greysanatomy
- gtaonline
- halifax
- halo
- headphones
- hearthstone
- heroesofthestorm
- hiking
- hockey
- hockeyjerseys
- hockeyplayers
- houston
- howardstern
- hungary
- india
- indonesia
- intermittentfasting
- iphone
- italy
- jailbreak
- japanesestreetwear
- japanlife
- jobs
- kansascity
- keto
- korea
- lakers
- leafs
- leagueoflegends
- leangains
- learnpython
- legaladvice
- longboarding
- loseit
- lucifer
- makeupexchange
- malaysia
- malefashion
- malefashionadvice
- malehairadvice
- malelivingspace
- marvelmemes
- marvelstudios
- medical_advice
- melbourne
- memes
- mexico
- migraine
- minnesotatwins
- minnesotavikings
- mw4
- mylittlepony
- nashville
- nattyorjuice
- nbadiscussion
- netflix
- newsokur
- newzealand
- nfl
- nhl
- norge
- nosleep
- nova
- nrl
- nvidia
- nyjets
- orangecounty
- orangetheory
- osugame
- overlord
- pathofexile
- pcmasterrace
- peloton
- pesmobile
- philadelphia
- phillies
- phoenix
- piercing
- pittsburgh
- playrust
- podemos
- pokemon
- pokemongo
- pokemontrades
- portugal
- poshmark
- powerlifting
- progresspics
- raleigh
- ravens
- rawdenim
- realmadrid
- reddeadredemption
- reddevils
- redsox
- rickandmorty
- ripcity
- riverdale
- roadtrip
- rolex
- rollercoasters
- rpdrcringe
- rugbyunion
- runescape
- running
- rupaulsdragrace
- rva
- sanantonio
- sandiego
- sanfrancisco
- saskatoon
- scifi
- seinfeld
- serbia
- shield
- sixers
- skiing
- skyrim
- smashbros
- sneakermarket
- snowboarding
- soccer
- solotravel
- southpark
- sports
- sportsbook
- starbucks
- starcitizen
- startrek
- steelers
- stevenuniverse
- stlouisblues
- streetwearstartup
- summonerswar
- suns
- survivor
- sweden
- swoleacceptance
- sydney
- sysadmin
- tampabayrays
- tattoos
- techsupport
- tennis
- tf2
- the100
- thebachelor
- thedivision
- thenetherlands
- thesims
- thesopranos
- thewalkingdead
- tipofmytongue
- titanfolk
- torontoraptors
- totalwar
- touhou
- trailerparkboys
- translator
- vagabond
- vancouver
- vanderpumprules
- vegan
- vzla
- warriors
- weightroom
- westworld
- wicked_edge
- wow
- xboxone
- xxfitness
- yeezys
- yoga
- yugioh
- zerocarb
- AMCsAList
- AMD_Stock
- Accounting
- AusFinance
- Bestbuy
- Bitcoin
- BitcoinMarkets
- Construction
- CreditCards
- CryptoCurrencies
- CryptoMarkets
- Ebay
- Entrepreneur
- Etsy
- FinancialCareers
- Forex
- HomeDepot
- Insurance
- KinFoundation
- LawSchool
- LitecoinMarkets
- Monero
- OfficeDepot
- PersonalFinanceCanada
- PickAnAndroidForMe
- Ripple
- RobinHood
- Scams
- StockMarket
- StudentLoans
- Target
- TheOCS
- Truckers
- Vechain
- WorkOnline
- amateurradio
- badeconomics
- beermoney
- bitcoincashSV
- btc
- churningcanada
- consulting
- couriersofreddit
- digitalnomad
- doordash
- dropship
- economy
- eos
- ethereum
- ethtrader
- excel
- finance
- forhire
- gofundme
- grubhubdrivers
- lyftdrivers
- marketing
- mturk
- nanocurrency
- options
- realestateinvesting
- sales
- shopify
- signupsforpay
- smallbusiness
- startups
- tax
- wallstreetbets
- walmart
